### ISSUE TITLE
"Delete my account" is not updated when changing the language

### ISSUE THREAD

**Issue by mrtndwrd** [openedx/frontend-app-account#622]
Steps to reproduce (on https://apps.demo.openedx.overhang.io/, I assume they run the newest version of the MFE to date):

1. Create an account and log in
2. Go to `/account`
3. Change the language, for example to Spanish

Expected result:

The whole page is shown in the new language

Actual result:

The page is shown in the new language, but the "Delete my account" section is still in English

![image](https://user-images.githubusercontent.com/832723/184618706-427c4c44-0544-4563-8440-e84d6876a57e.png)

When I refresh, the page is fully in English, so it's not a missing translation.

**Comment by heldersepu** [comment]
Seem to be working fine now:
https://apps.demo.openedx.overhang.io/account/#delete-account

![image](https://github.com/openedx/frontend-app-account/assets/545474/fc1e15f6-dcb1-4e0b-a6ea-973fab302f4a)

**Comment by heldersepu** [comment]
From a code perspective it seems that code/translation has been there for a while:
https://github.com/openedx/frontend-app-account/blame/open-release/palm.master/src/i18n/messages/es_419.json#L141

Maybe it was a hiccup?!?
I'm not able to reproduce

**Comment by mrtndwrd** [comment]
I don't think it was a hiccup, because I had this problem consistently on different environments. I don't work on that project anymore though, so I can't tell you if the problem is fixed or not. I can imagine some seemingly unrelated change fixed it, so if you can't reproduce it, feel free to close this issue.

**Comment by mrtndwrd** [comment]
I think i made a mistake with the original message by the way:

> When I refresh, the page is fully in English, so it's not a missing translation.

Should have been "... fully in *Spanish*".

The point being that the text is only wrong after you've changed the language and have not refreshed the page yet. So yes, the translation was always there, but it wasn't used correctly after changing the language.

**Comment by mrtndwrd** [comment]
OK sorry for posting so many times. I just checked on the original link and it seems like the issue is indeed resolved.
